tourny_tracker/config/routes.rb
Rails.application.routes.draw do
  # Index page/route
  root 'tournaments#index'

  # Devise handles all of the user routing
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Routing for showing user profile
  resources :users, only: [:show]

  # Routes for Tournaments
  resources :tournaments do
    resources :teams, except: [:index, :show]
    # get 'join' => 'teams#join'
    resources :teammates, only: [:new, :create, :destroy]
  end

  resources :teams, only: [:show]
end

tourny_tracker/app/models/tournament.rb
class Tournament < ApplicationRecord
  # Assocaitions
  belongs_to :creator, class_name: "User", foreign_key: "created_by"
  belongs_to :elimination_type
  belongs_to :game
  belongs_to :tournament_state
  has_and_belongs_to_many :hosts, class_name: "User"
  has_one :grouping_info, inverse_of: :tournament 
  has_many :groups
  has_many :teams, through: :groups
  has_many :members, through: :teams, source: :users
  # Validations
  validates :name, presence: true, uniqueness: true, length: {maximum: 20}, allow_blank: false
	validates :team_count, presence: true, numericality: { even: true }
  validates :elimination_type, presence: true
	validates :team_size, presence: true
  validates :game, presence: true
  validates :tournament_state, presence: true
  validates :creator, presence: true
  validates_inclusion_of :use_grouping, :in => [true, false]
  validate :has_grouping_info?
  validate :number_of_groups_valid
  # Callbacks
  before_save :create_groups
  after_initialize :set_defaults
  # Other attributes accepted
  accepts_nested_attributes_for :grouping_info, allow_destroy: false, reject_if: :should_not_create_grouping?

  # Tells if the given user is the creator of this tournament
  def is_user_creator?(user)
    if(user.nil?)
      false
    else
      self.creator == user
    end
  end

  # Tells if the given user is a host for this tournament
  def is_user_host?(user)
    if(user.nil?)
      false
    else
      self.hosts.exists?(user.id) || self.creator == user
    end
  end

  # This returns a list of groups that are not full
  def available_groups
    # Create the array that will hold the list fo groups
    avail_groups = Array.new
    # Now find the onces that are not full
    self.groups.each do |group|
      unless group.is_full?
        avail_groups << group
      end
    end
  end

  # since if groups should not be used creates a single group to hold teams,
  # this method returns that group
  def groupless_group
    self.groups.first
  end

  # Tells if a user is already participating in this tournament
  def is_user_participant?(user)
    self.members.exists?(user.id)
  end

  # Determines if all teams spots are filled
  def is_ready?
    ready = true
    self.groups.each do |group|
      unless group.is_full?
        ready = false 
        break
      end
    end
    ready
  end

  # Starts the tournament
  def start_tournament
    if is_ready?
      if self.use_grouping
        if self.grouping_info.elimination_type.name == "Round Robin"
          self.groups.each do |group|
            gen_round_robin_matches(group.teams)
          end
        elsif self.grouping_info.elimination_type.name == "Single Elimination"

        end
      else
        if self.elimination_type.name == "Round Robin"
          gen_round_robin_matches(groupless_group.teams)
        end
      end
    end
  end

  private
    # ================ Validation Methods ==========
    # Make sure there is a grouping info object if use_grouping is true
    def has_grouping_info?
      if self.use_grouping && self.grouping_info.nil?
        errors.add :base, "There needs to be grouping info for this tournament"
      elsif !self.use_grouping && !self.grouping_info.nil?
        errors.add :base, "No need to for grouping info for this tournament"
      end
    end

    def should_not_create_grouping?
      !self.use_grouping
    end

    def number_of_groups_valid
      if(self.use_grouping)
        errors.add :base, "Number of groups reached." if self.groups.count >= self.grouping_info.group_count
      else
        errors.add :base, "Number of groups reached." if self.groups.count >= 1
      end
    end

    # ================ Call back Methods ==========
    def set_defaults
      self.use_grouping = false if self.use_grouping.nil?
      self.tournament_state ||= TournamentState.first
    end

    def create_groups
      if self.use_grouping
        self.team_count = self.grouping_info.group_count * self.grouping_info.teams_per_group
        # First get a list of group names for the number of groups in this tournament
        group_names = GroupName.order('name').limit(self.grouping_info.group_count)
        # Now iteraet over that lits to create the acutal groups
        group_names.each do |g|
          self.groups << Group.new(group_name: g)
        end
      else
        # Otherwise there should not be grouping info
        self.grouping_info = nil
        #Create a single group that will hold all the teams
        team_group_name = GroupName.last
        self.groups << Group.new(group_name: team_group_name)
      end
    end

    # will generate and save matches necessary for round roubin from a list of teams
    def gen_round_robin_matches(teams)
      # Make sure the team object is not nil
      logger.info teams.count
      if teams.any?
        for h in 0..teams.count-1
          for a in h+1..teams.count-1
            Match.create(home_team_id: teams[h].id, away_team_id: teams[a].id, round: :prelims).save!
          end
        end
      end
    end

end

tourny_tracker/app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]

  def index
    @tournaments = Tournament.all
  end

  def show
    @tournament = find_tournament
  end

  def new
    @tournament = Tournament.new
    @tournament.creator = current_user
    @tournament.build_grouping_info
  end 

  def create
    # Build the tournament object using the parameters passed in
    @tournament = Tournament.new(tournament_params)
    # Set the creator of the tournament
    @tournament.creator = current_user
    # Handle the different response types
    if @tournament.save
      redirect_to tournament_path(@tournament)
    else
      respond_to do |format|
        format.json { render json: @tournament.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @tournament = find_tournament
  end

  def update
    @tournament = find_tournament
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to tournament_path(@tournament) }
      else
        format.json { render json: @tournament.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy

  end

  private
    def find_tournament
      @tournament = Tournament.find(params[:id])
    end

    def tournament_params
      params.require(:tournament).permit(:name, :team_count, :use_grouping, :elimination_type_id, :team_size, :game_id, :tournament_state, grouping_info_attributes: [:elimination_type_id, :group_count, :teams_per_group, :playoffs_advanced])
    end
end

tourny_tracker/app/helpers/tournaments_helper.rb
module TournamentsHelper
end

tourny_tracker/app/views/tournaments/_tournament.html.slim
= link_to tournament_path(tournament), class: 'tournament', id: "tournament_#{tournament.id}"
  .header
    h5.label-header = tournament.name
    = image_tag 'cup.png'
  .tournament-info
    span.label-header Game: 
    span = tournament.game.name
    br
    span.label-header State: 
    span = tournament.tournament_state.state
    br
    span.label-header Created by: 
    span = tournament.creator.first_name

tourny_tracker/app/views/tournaments/_tournament_form.html.slim
.modal-header
  h2.modal-title
    = @tournament.new_record? ? 'New Tournament Info' : 'Edit Tournament Info'
= form_for @tournament, remote: true do |f|
  .modal-body.form-horizontal
    #error_explanation.bg-danger.text-danger
    .form-group
      = f.label "Name:", class: "control-label col-sm-2"
      .col-sm-10
        = f.text_field :name, placeholder: "Name", autofocus: true, class: "form-control"
    .form-group
      = f.label "Gouping:", class: "control-label col-sm-2"
      .col-sm-1
        = f.check_box :use_grouping, disabled: !@tournament.new_record?, class: "checkbox"
      .col-sm-9
        span Use Groups
    #tournament-form-group-section
      = f.fields_for :grouping_info do |ff|
        .form-group
          = ff.label "Group Elimination:", class: "control-label col-sm-2"
          .col-sm-10
            = ff.collection_select :elimination_type_id, EliminationType.all,:id,:name, {}, readonly: !@tournament.new_record?, class: "form-control"
        .form-group
          = ff.label "Groups:", class: "control-label col-sm-2"
          .col-sm-10
            = ff.number_field :group_count, placeholder: "Number of groups, if any (even)", readonly: !@tournament.new_record?, class: "form-control"
        .form-group
          = ff.label "Teams per Group", class: "control-label col-sm-2"
          .col-sm-10
            = ff.number_field :teams_per_group, placeholder: "Number of teams per groups (even)", readonly: !@tournament.new_record?, class: "form-control"
        .form-group
          = ff.label "Playoff Count", class: "control-label col-sm-2"
          .col-sm-10
            = ff.number_field :playoffs_advanced, placeholder: "Number of teams to move on to playoffs (even)", readonly: !@tournament.new_record?, class: "form-control"
    .form-group
      = f.label "Elimination:", class: "control-label col-sm-2"
      .col-sm-10
        = f.collection_select :elimination_type_id, EliminationType.all,:id,:name, {}, readonly: !@tournament.new_record?, class: "form-control"
    .form-group
      = f.label "Teams:", class: "control-label col-sm-2"
      .col-sm-10
        = f.number_field :team_count, placeholder: "Number of teams in tournament (even)", readonly: !@tournament.new_record?, class: "form-control"
    .form-group
      = f.label "Team Size:", class: "control-label col-sm-2"
      .col-sm-10
        = f.number_field :team_size, placeholder: "Number of teammates per teams", readonly: !@tournament.new_record?, class: "form-control"
    .form-group
      = f.label "Game:", class: "control-label col-sm-2"
      .col-sm-10
        = f.collection_select :game_id, Game.order(:name),:id,:name, {}, readonly: !@tournament.new_record?, class: "form-control"
  .modal-footer
    a.btn.btn-default data-dismiss="modal" href="#"  Close
    = f.submit :submit, class: "btn btn-primary"

tourny_tracker/app/views/tournaments/edit.js.erb
$('#modal-window').modal(); 
$('#modal-content').html("<%= escape_javascript(render("tournament_form")) %>");
// Hide or show the use_grouping section initially base on the value of the checkbox
if ($("#tournament_use_grouping").prop("checked")){
  $("#tournament-form-group-section").show();
}else{
  $("#tournament-form-group-section").hide();
}
// This is to show or hide the group portion of the form when the use_grouping checkbox is checked or not
$(document).ready(function(){
  $("#tournament_use_grouping").click(function (){
    if ($("#tournament_use_grouping").prop("checked")){
      $("#tournament-form-group-section").show();
    }else{
      $("#tournament-form-group-section").hide();
    }              
  });
});

tourny_tracker/app/views/tournaments/index.html.slim
.row
  #tournaments-container.col-md-10
    - if @tournaments.any?
      = render @tournaments
    - else
      - if user_signed_in?
        p There are no tournaments currently, click on + to create a new one.
      - else
        p There are no tournaments currently, sign in to create one.
- if user_signed_in?
  = link_to new_tournament_path, remote: true, class: "btn btn-primary", id: "floating-action-button"
    i.glyphicon.glyphicon-plus
  / #tournament-modal.modal.fade
  /   .modal-dialog
  /     #tournament_form.modal-content
  

tourny_tracker/app/views/tournaments/new.js.erb
$('#modal-window').modal(); 
$('#modal-content').html("<%= escape_javascript(render("tournament_form")) %>");
// Hide or show the use_grouping section initially base on the value of the checkbox
if ($("#tournament_use_grouping").prop("checked")){
  $("#tournament-form-group-section").show();
}else{
  $("#tournament-form-group-section").hide();
}
// This is to show or hide the group portion of the form when the use_grouping checkbox is checked or not
$(document).ready(function(){
  $("#tournament_use_grouping").click(function (){
    if ($("#tournament_use_grouping").prop("checked")){
      $("#tournament-form-group-section").show();
    }else{
      $("#tournament-form-group-section").hide();
    }              
  });
});

tourny_tracker/app/views/tournaments/show.html.slim
#tournament-show-header.row
  .col-md-11
    h2 = @tournament.name
  .col-md-1
    - if user_signed_in?
      - unless @tournament.is_user_participant?(current_user)
        .dropdown
          button.btn.btn-primary.dropdown-toggle data-toggle="dropdown"
            | Join Tournament 
            span.caret
          ul.dropdown-menu
            li = link_to 'Create new Team', new_tournament_team_path(@tournament), remote: true
            li = link_to 'Join existing Team', new_tournament_teammate_path(@tournament), remote: true
      - else
        = link_to 'Leave tournament', "#", class: "btn btn-danger"
br
.row
  .col-md-12
    ul.nav.nav-tabs
      li.active 
        a data-toggle="tab" href="#standings" Standings
      li 
        a data-toggle="tab" href="#games" Games
      li 
        a data-toggle="tab" href="#brackets" Brackets
    .tab-content
      #standings.tab-pane.fade.in.active
        = render @tournament.groups
      #games.tab-pane.fade.in
        P Games content
      #brackets.tab-pane.fade.in
        p bracket content
#tournament-show-footer.row
  .col-md-10
    span Hosted by: 
    = link_to user_path(@tournament.creator)
      = @tournament.creator.first_name
    - @tournament.hosts.each do |host|
      span , 
      = link_to user_path(host)
        = host.first_name
  .col-md-2
    - if @tournament.is_user_creator?(current_user)
      = link_to 'Delete', "#", class: "btn btn-danger tournament-show-footer-button"
    - if @tournament.is_user_host?(current_user)
      = link_to 'Edit', edit_tournament_path(@tournament), remote: true, class: "btn btn-default tournament-show-footer-button"
    



    
    